---
- name: Validar y reiniciar Nginx
  block:
    - name: Validar configuraci√≥n de Nginx
      command: nginx -t
      register: nginx_test
      changed_when: false

    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted

