- name: Instalar firewalld
  yum:
    name: firewalld
    state: present

- name: Arrancar y habilitar firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Abrir puerto SSH (22) con firewalld
  command: firewall-cmd --permanent --add-service=ssh
  become: yes
  notify: reload firewalld

- name: Abrir puerto HTTP (80) con firewalld
  command: firewall-cmd --permanent --add-service=http
  become: yes
  notify: reload firewalld

- name: Instalar fail2ban
  yum:
    name: fail2ban
    state: present

- name: Activar fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes

